# @package _group_

name: java-small
path: C:\Users\Igor\IdeaProjects\ide-plugin\dataset\java-small
type: lazy
lazy_reader_type: with_cache
split_strategy: java-small

usage_vocab_max_size:
target_vocab_max_size:
usage_vocab_min_freq: 3
target_vocab_min_freq: 2