# @package _group_
name_of_run: test_config
checkpoints_dir: checkpoints/

usage_tokenizer_type: sub_token
target_tokenizer_type: camel_case
max_epochs: 10
max_sequence_length: 11
max_num_usages: 10
max_target_length: 6
embedding_dim: 16
usage_embedding_dim: 16
target_embedding_dim: 16
num_heads: 2
num_encoder_layers: 1
num_decoder_layers: 2
num_usage_layers: 1
dropout: 0.1
max_lr: 5e-4
batch_size: 8
sequence_encoder_type: transformer
gpus: 1
