defaults:
  - model: transformer_encoder2

dataset_path: C:\Users\Igor\IdeaProjects\ide-plugin\build\idea-sandbox\system\dataset\java-small\
dataset_split_strategy: java-small # or mixed
checkpoints_dir: checkpoints/
show_in_wandb: True
