dataset_path: C:\Users\Igor\IdeaProjects\ide-plugin\build\idea-sandbox\system\dataset\batik_dataset.json
name_of_run: test-run
max_epochs: 100

max_sequence_length: 6
max_num_usages: 10
max_target_length: 6
embedding_dim: 32
usage_embedding_dim: 32
target_embedding_dim: 32
num_heads: 4
num_encoder_layers: 2
num_decoder_layers: 2
num_usage_layers: 4
dropout: 0.1
lr: 1e-4
batch_size: 16
sequence_encoder_type: transformer
gpus: 1
